title_name = "Burnout Revenge"
title_id = "454107DC" # TQ-2001

hash = [
    "D629EA67090E3137" # default.xex (Title Update 0)
]

#media_id = "223759FA" # Disc (USA, Europe)

[[patch]]
   name = "Debug menu"
    desc = "Replaces the extras menu"
    author = "Nehalem"
    is_enabled = true

    [[patch.be32]]
        address = 0x820394bc
        value = 0x82206500

[[patch]]
   name = "Crash vehicles in all modes"
    desc = "Selectable crash vehicles in all modes"
    author = "Nehalem"
    is_enabled = true

    [[patch.be16]]
        address = 0x820fb1ac
        value = 0x4800

[[patch]]
   name = "Ignore road rage event timer"
    desc = "Prevent game ending when the timer reaches 0 in road rage events"
    author = "Nehalem"
    is_enabled = true

    [[patch.be16]]
        address = 0x82141e04
        value = 0x4800

    # Disable road rage timer display
    [[patch.be32]]
        address = 0x821a8c4c
        value = 0x60000000

[[patch]]
   name = "Disable game mode HUD"
    desc = "Prevent the game to display the game mode HUD component"
    author = "Nehalem"
    is_enabled = true

    [[patch.be32]]
        address = 0x821a4090
        value = 0x4e800020

[[patch]]
   name = "Disable rating HUD"
    desc = "Prevent the game to display the rating HUD component"
    author = "Nehalem"
    is_enabled = true

    [[patch.be32]]
        address = 0x821a842c
        value = 0x60000000

[[patch]]
   name = "Offline standing start"
    desc = "Standing start instead of rolling start in offline modes, boost start enabled for Race, Burning Lap & Eliminator"
    author = "Nehalem"
    is_enabled = true

    [[patch.be8]]
        address = 0x82122851
        value = 0x63
    [[patch.be32]]
        address = 0x82138730
        value = 0x38600000
    [[patch.be32]]
        address = 0x82138774
        value = 0x3fe08201
    [[patch.be32]]
        address = 0x82138778
        value = 0xc01f76b0
    [[patch.be32]]
        address = 0x8213877c
        value = 0x4800004c

[[patch]]
   name = "Disable camera speed shake"
    desc = "Prevent the camera from shaking while driving at high speeds"
    author = "Nehalem"
    is_enabled = true

    [[patch.be32]]
        address = 0x822fcf58
        value = 0x4e800020

[[patch]]
   name = "Super camera speed shake"
    desc = "ShaAaAaAake"
    author = "Nehalem"
    is_enabled = true

    [[patch.be32]]
        address = 0x82694cbc
        value = 0x40a00000
    [[patch.be32]]
        address = 0x82694cd4
        value = 0x40a00000

[[patch]]
   name = "Hyper camera speed shake"
    desc = "SHAAAAAAKE"
    author = "Nehalem"
    is_enabled = true

    [[patch.be32]]
        address = 0x82694cbc
        value = 0x41a00000
    [[patch.be32]]
        address = 0x82694cd4
        value = 0x41a00000
        
[[patch]]
   name = "Uber camera speed shake"
    desc = "YEAAAHHHHHHH"
    author = "Nehalem"
    is_enabled = true

    [[patch.be32]]
        address = 0x82694cbc
        value = 0x42c80000
    [[patch.be32]]
        address = 0x82694cd4
        value = 0x42c80000
